/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Proveedores;

import GUI_Login.GUI_Login;
import GUI_Login.GUI_Opciones;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Ethan
 */
public class GUI_Proveedores extends javax.swing.JFrame {
    String rutIngresado;
    /**
     * Creates new form GUI_Proveedores
     */
    
    public GUI_Proveedores(String rutLogin) throws SQLException {
        initComponents();
        rutIngresado = rutLogin;
        
        //se obtienen datos
        DefaultTableModel df = new DBProveedores().cargarProveedores();
        
        //config de tabla
        tablaProveedores.setModel(df);
        tablaProveedores.setDefaultEditor(Object.class, null);
        JTableHeader tableHeader = tablaProveedores.getTableHeader();
        tableHeader.setReorderingAllowed(false);
        
        jScrollPane2.setVisible(false);
        botonReiniciar.setEnabled(false);    
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscar = new javax.swing.JButton();
        botonReiniciar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        barraBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInsumos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBuscar.setBackground(new java.awt.Color(203, 243, 236));
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 80, -1));

        botonReiniciar.setBackground(new java.awt.Color(51, 153, 255));
        botonReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        botonReiniciar.setText("REINICIAR TABLA");
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 140, 30));

        botonVolver.setBackground(new java.awt.Color(51, 153, 255));
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 30));

        cerrarSesion.setBackground(new java.awt.Color(51, 153, 255));
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 110, 30));

        jLabel2.setBackground(new java.awt.Color(174, 220, 213));
        jLabel2.setText("INGRESE NOMBRE INSUMO:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 20));

        barraBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(barraBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 780, -1));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Proveedor", "Direccion", "Correo", "Telefono contacto"
            }
        ));
        jScrollPane1.setViewportView(tablaProveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1120, -1));

        tablaInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Proveedor", "Insumo", "Cantidad", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tablaInsumos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 180, 1120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1210, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        this.dispose();
        new GUI_Login().setVisible(true);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        new GUI_Opciones(rutIngresado).setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        jScrollPane2.setVisible(false);
        jScrollPane1.setVisible(true);
        barraBuscar.setText("");
        botonReiniciar.setEnabled(false);
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void barraBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBuscarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        
        try {
            jScrollPane2.setVisible(true);
            jScrollPane1.setVisible(false);
            botonReiniciar.setEnabled(true);
            String busqueda = barraBuscar.getText();
            DefaultTableModel df2 = new DBProveedores().cargarInsumos(busqueda);
            
            //config de tabla de insumos
            tablaInsumos.setModel(df2);
            tablaInsumos.setDefaultEditor(Object.class, null);
            JTableHeader tableHeader = tablaInsumos.getTableHeader();
            tableHeader.setReorderingAllowed(false);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rut = "";
                try {
                    new GUI_Proveedores(rut).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBuscar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaInsumos;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
