/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Pedidos;

import GUI_Login.GUI_Login;
import GUI_Login.GUI_Opciones;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Ethan
 */
public class GUI_Pedidos extends javax.swing.JFrame {
    String rutIngresado;
    /**
     * Creates new form GUI_Pedidos
     */
    public GUI_Pedidos(String rutLogin) throws SQLException {
        initComponents();
        rutIngresado = rutLogin;
        
        //se obtienen datos
        DefaultTableModel df = new DBPedidos().cargarPedidos();
        
        //config de tabla
        tablaPedidos.setModel(df);
        tablaPedidos.setDefaultEditor(Object.class, null);
        JTableHeader tableHeader = tablaPedidos.getTableHeader();
        tableHeader.setReorderingAllowed(false);
        
        jScrollPane2.setVisible(false);
        botonReiniciar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        barraFecha = new javax.swing.JTextField();
        barraInsumo = new javax.swing.JTextField();
        barraProveedor = new javax.swing.JTextField();
        botonAnual = new javax.swing.JButton();
        botonMensual = new javax.swing.JButton();
        botonReiniciar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFiltrada = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1208, 696));
        setPreferredSize(new java.awt.Dimension(1208, 696));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("FECHA (DÍA/MES/AÑO):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 220, 40));

        jLabel3.setText("NOMBRE INSUMO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 220, 40));

        jLabel2.setText("PROVEEDOR:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 220, 40));

        botonBuscar.setBackground(new java.awt.Color(203, 243, 236));
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 120, 30));

        barraFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraFechaActionPerformed(evt);
            }
        });
        getContentPane().add(barraFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 240, 30));

        barraInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraInsumoActionPerformed(evt);
            }
        });
        getContentPane().add(barraInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 240, 30));

        barraProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(barraProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        botonAnual.setBackground(new java.awt.Color(51, 153, 255));
        botonAnual.setForeground(new java.awt.Color(255, 255, 255));
        botonAnual.setText("GASTOS ANUALES");
        botonAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnualActionPerformed(evt);
            }
        });
        getContentPane().add(botonAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, 260, 30));

        botonMensual.setBackground(new java.awt.Color(51, 153, 255));
        botonMensual.setForeground(new java.awt.Color(255, 255, 255));
        botonMensual.setText("GASTOS MENSUALES");
        botonMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMensualActionPerformed(evt);
            }
        });
        getContentPane().add(botonMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 260, 30));

        botonReiniciar.setBackground(new java.awt.Color(51, 153, 255));
        botonReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        botonReiniciar.setText("REINICIAR TABLA");
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 260, 30));

        botonAgregar.setBackground(new java.awt.Color(51, 153, 255));
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setText("AGREGAR PEDIDO");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 240, 30));

        cerrarSesion.setBackground(new java.awt.Color(51, 153, 255));
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 110, 30));

        botonVolver.setBackground(new java.awt.Color(51, 153, 255));
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 30));

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1140, -1));

        tablaFiltrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaFiltrada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        new GUI_Opciones(rutIngresado).setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        this.dispose();
        new GUI_Login().setVisible(true);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        new GUI_AñadirPedido(rutIngresado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void barraInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraInsumoActionPerformed

    private void barraFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraFechaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try {
            String proveedor = barraProveedor.getText().trim();
            String pedido = barraInsumo.getText().trim();
            String fecha = barraFecha.getText().trim();
            
            if(proveedor.isEmpty() && pedido.isEmpty() && fecha.isEmpty()){
                JOptionPane.showMessageDialog(null, "RELLENAR POR LO MENOS UN FILTRO DE BUSQUEDA","ALERTA", JOptionPane.WARNING_MESSAGE);
            }
            else{  
                DefaultTableModel df2 = new DBPedidos().cargarFiltros(proveedor, pedido, fecha);
                tablaFiltrada.setModel(df2);
                tablaFiltrada.setDefaultEditor(Object.class, null);
                JTableHeader tableHeader = tablaFiltrada.getTableHeader();
                tableHeader.setReorderingAllowed(false);
        
                jScrollPane2.setVisible(true);
                jScrollPane1.setVisible(false);
                botonReiniciar.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void barraProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraProveedorActionPerformed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        jScrollPane2.setVisible(false);
        jScrollPane1.setVisible(true);
        barraProveedor.setText("");
        barraInsumo.setText("");
        barraFecha.setText("");
        botonReiniciar.setEnabled(false);
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void botonMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMensualActionPerformed
        try{
            DefaultTableModel df3 = new DBPedidos().cargarGastosMensuales();
            tablaFiltrada.setModel(df3);
            tablaFiltrada.setDefaultEditor(Object.class, null);
            JTableHeader tableHeader = tablaFiltrada.getTableHeader();
            tableHeader.setReorderingAllowed(false);
        
            jScrollPane2.setVisible(true);
            jScrollPane1.setVisible(false);
            botonReiniciar.setEnabled(true);
        } catch (SQLException ex){
            Logger.getLogger(GUI_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonMensualActionPerformed

    private void botonAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnualActionPerformed
        try{
            DefaultTableModel df3 = new DBPedidos().cargarGastosAnuales();
            tablaFiltrada.setModel(df3);
            tablaFiltrada.setDefaultEditor(Object.class, null);
            JTableHeader tableHeader = tablaFiltrada.getTableHeader();
            tableHeader.setReorderingAllowed(false);
        
            jScrollPane2.setVisible(true);
            jScrollPane1.setVisible(false);
            botonReiniciar.setEnabled(true);
        } catch (SQLException ex){
            Logger.getLogger(GUI_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rut = "";
                try {
                    new GUI_Pedidos(rut).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraFecha;
    private javax.swing.JTextField barraInsumo;
    private javax.swing.JTextField barraProveedor;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAnual;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonMensual;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaFiltrada;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
