/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Pedidos;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Ethan
 */
public class GUI_AñadirPedido extends javax.swing.JFrame {
    String rutIngresado ;
    /**
     * Creates new form GUI_AñadirPedido
     */
    public GUI_AñadirPedido(String rutLogin) {
        
        rutIngresado = rutLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        barraID.setEditable(false);
        barraID.setText(String.valueOf(new DBPedidos().devolverID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonX = new javax.swing.JLabel();
        barraRut = new javax.swing.JTextField();
        barraUnidad = new javax.swing.JTextField();
        barraAnio = new javax.swing.JTextField();
        barraMes = new javax.swing.JTextField();
        barraCantidad = new javax.swing.JTextField();
        barraPedido = new javax.swing.JTextField();
        barraID = new javax.swing.JTextField();
        barraPrecio = new javax.swing.JTextField();
        barraDia = new javax.swing.JTextField();
        botonAnadir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equis.png"))); // NOI18N
        botonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonXMouseClicked(evt);
            }
        });
        getContentPane().add(botonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 30, 30));

        barraRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraRutActionPerformed(evt);
            }
        });
        barraRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraRutKeyPressed(evt);
            }
        });
        getContentPane().add(barraRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 180, 30));

        barraUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraUnidadActionPerformed(evt);
            }
        });
        barraUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraUnidadKeyPressed(evt);
            }
        });
        getContentPane().add(barraUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 180, 30));

        barraAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraAnioActionPerformed(evt);
            }
        });
        barraAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraAnioKeyPressed(evt);
            }
        });
        getContentPane().add(barraAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 180, 30));

        barraMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMesActionPerformed(evt);
            }
        });
        barraMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraMesKeyPressed(evt);
            }
        });
        getContentPane().add(barraMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 180, 30));

        barraCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraCantidadActionPerformed(evt);
            }
        });
        barraCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraCantidadKeyPressed(evt);
            }
        });
        getContentPane().add(barraCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 180, 30));

        barraPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPedidoActionPerformed(evt);
            }
        });
        barraPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraPedidoKeyPressed(evt);
            }
        });
        getContentPane().add(barraPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 30));

        barraID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraIDActionPerformed(evt);
            }
        });
        barraID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraIDKeyPressed(evt);
            }
        });
        getContentPane().add(barraID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 180, 30));

        barraPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPrecioActionPerformed(evt);
            }
        });
        barraPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraPrecioKeyPressed(evt);
            }
        });
        getContentPane().add(barraPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 180, 30));

        barraDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraDiaActionPerformed(evt);
            }
        });
        barraDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraDiaKeyPressed(evt);
            }
        });
        getContentPane().add(barraDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 180, 30));

        botonAnadir.setBackground(new java.awt.Color(51, 153, 255));
        botonAnadir.setForeground(new java.awt.Color(255, 255, 255));
        botonAnadir.setText("Añadir");
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnadirMouseClicked(evt);
            }
        });
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(botonAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 210, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RUT PROVEEDOR");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 170, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNIDAD METRICA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AÑO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CANTIDAD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MES");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 160, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PRECIO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INSUMO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID PEDIDO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DIA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Añadir Pedido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-empl.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 740));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-empl.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonXMouseClicked
        this.dispose();
        try {
            String rut = "";
            new GUI_Pedidos(rut).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_AñadirPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonXMouseClicked

    private void barraRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraRutActionPerformed

    private void barraRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraRutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraRutKeyPressed

    private void barraUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraUnidadActionPerformed

    private void barraUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraUnidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraUnidadKeyPressed

    private void barraAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraAnioActionPerformed

    private void barraAnioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraAnioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraAnioKeyPressed

    private void barraMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraMesActionPerformed

    private void barraMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraMesKeyPressed

    }//GEN-LAST:event_barraMesKeyPressed

    private void barraIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraIDActionPerformed

    private void barraIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraIDKeyPressed

    private void barraPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPrecioActionPerformed

    private void barraPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPrecioKeyPressed

    private void barraDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraDiaActionPerformed

    private void barraDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraDiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraDiaKeyPressed

    private void botonAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseClicked
        try {
            
            String id_string = barraID.getText().trim();
            int id = Integer.parseInt(id_string);
            String dia = barraDia.getText().trim();
            String pedido = barraPedido.getText().trim();
            String mes = barraMes.getText().trim();
            String cantidad = barraCantidad.getText().trim();
            String anio = barraAnio.getText().trim();
            String unidad_metrica = barraUnidad.getText().trim();
            String rut_proveedor = barraRut.getText().trim();
            int precio = Integer.parseInt(barraPrecio.getText().trim());
            if(id_string.isEmpty() || dia.isEmpty() || pedido.isEmpty() || mes.isEmpty() || cantidad.isEmpty() || anio.isEmpty() || unidad_metrica.isEmpty() || rut_proveedor.isEmpty() || barraPrecio.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "RELLENAR TODAS LAS OPCIONES","ALERTA", JOptionPane.WARNING_MESSAGE);
            }
            else{
                boolean aprobado = new DBPedidos().anadir(id, pedido, cantidad, unidad_metrica, precio, dia, mes, anio, rut_proveedor, rutIngresado);

                if (aprobado) {
                    JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                    this.dispose();
                    new GUI_Pedidos(rutIngresado).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al ingresar los datos a la base de datos");
                }
            }
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor de precio, cantidad, dia, mes y año deben ser ingresados como numeros.");
        } catch (SQLException ex) {
            Logger.getLogger(GUI_AñadirPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAnadirMouseClicked

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed

    }//GEN-LAST:event_botonAnadirActionPerformed

    private void barraPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraPedidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPedidoKeyPressed

    private void barraPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPedidoActionPerformed

    private void barraCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraCantidadKeyPressed

    private void barraCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_AñadirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_AñadirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_AñadirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_AñadirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rut = "";
                new GUI_AñadirPedido(rut).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraAnio;
    private javax.swing.JTextField barraCantidad;
    private javax.swing.JTextField barraDia;
    private javax.swing.JTextField barraID;
    private javax.swing.JTextField barraMes;
    private javax.swing.JTextField barraPedido;
    private javax.swing.JTextField barraPrecio;
    private javax.swing.JTextField barraRut;
    private javax.swing.JTextField barraUnidad;
    private javax.swing.JButton botonAnadir;
    private javax.swing.JLabel botonX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
