/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Boleta;

import GUI_Login.GUI_Login;
import GUI_Login.GUI_Opciones;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GUI_Boleta extends javax.swing.JFrame {

    String rutIngresado;

    /**
     * Creates new form GUI_Boleta
     *
     * @param rutLogin
     */
    public GUI_Boleta(String rutLogin) throws SQLException {
        rutIngresado = rutLogin;
        initComponents();

        DefaultTableModel df = new DefaultTableModel();
        df = new BDBoleta().cargarBoletas(df);
        Tabla.setModel(df);
        Tabla.setDefaultEditor(Object.class, null);

        labelAnio.setVisible(false);
        comboboxAnio.setVisible(false);
        comboboxMes.setVisible(false);
        labelMes.setVisible(false);

        Grafica.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                String selectedItem = (String) e.getItem();

                if ("Cantidad generada por cada empleado".equals(selectedItem)) {
                    labelAnio.setVisible(false);
                    comboboxAnio.setVisible(false);
                    comboboxMes.setVisible(false);
                    labelMes.setVisible(false);
                } else if ("Promedio generado en cada mes".equals(selectedItem)) {
                    labelAnio.setVisible(true);
                    comboboxAnio.setVisible(true);
                    comboboxMes.setVisible(false);
                    labelMes.setVisible(false);
                } else if ("Promedio de ventas anuales".equals(selectedItem)) {
                    labelAnio.setVisible(false);
                    comboboxAnio.setVisible(false);
                    comboboxMes.setVisible(false);
                    labelMes.setVisible(false);
                } else if ("Cantidad generada en un mes".equals(selectedItem)) {
                    labelAnio.setVisible(true);
                    comboboxAnio.setVisible(true);
                    comboboxMes.setVisible(true);
                    labelMes.setVisible(true);
                }

            }
        });

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelAnio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        canDesc = new javax.swing.JRadioButton();
        canAsc = new javax.swing.JRadioButton();
        anioDesc = new javax.swing.JRadioButton();
        anioAsc = new javax.swing.JRadioButton();
        mesAsc = new javax.swing.JRadioButton();
        mesDesc = new javax.swing.JRadioButton();
        diaAsc = new javax.swing.JRadioButton();
        diaDesc = new javax.swing.JRadioButton();
        labelMes = new javax.swing.JLabel();
        comboboxAnio = new javax.swing.JComboBox<>();
        comboboxMes = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        restablecer = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Grafica = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 480, 450));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 110, 30));

        labelAnio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelAnio.setForeground(new java.awt.Color(255, 255, 255));
        labelAnio.setText("Año");
        getContentPane().add(labelAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 40, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ordenar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 120, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Boleta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 40));

        canDesc.setText("Cantidad (Descendente)");
        canDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canDescActionPerformed(evt);
            }
        });
        getContentPane().add(canDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 180, -1));

        canAsc.setText("Cantidad (Ascendente)");
        canAsc.setToolTipText("");
        canAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canAscActionPerformed(evt);
            }
        });
        getContentPane().add(canAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 180, -1));

        anioDesc.setText("Año (Descendente)");
        anioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioDescActionPerformed(evt);
            }
        });
        getContentPane().add(anioDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 180, -1));

        anioAsc.setText("Año (Ascendente)");
        anioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioAscActionPerformed(evt);
            }
        });
        getContentPane().add(anioAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 180, -1));

        mesAsc.setText("Mes (Ascendente)");
        mesAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesAscActionPerformed(evt);
            }
        });
        getContentPane().add(mesAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 180, -1));

        mesDesc.setText("Mes (Descendente)");
        mesDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesDescActionPerformed(evt);
            }
        });
        getContentPane().add(mesDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 180, -1));

        diaAsc.setText("Dia (Ascendente)");
        diaAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaAscActionPerformed(evt);
            }
        });
        getContentPane().add(diaAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 180, -1));

        diaDesc.setText("Dia (Descendente)");
        diaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaDescActionPerformed(evt);
            }
        });
        getContentPane().add(diaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 180, -1));

        labelMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelMes.setForeground(new java.awt.Color(255, 255, 255));
        labelMes.setText("Mes");
        getContentPane().add(labelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 40, 30));

        comboboxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(comboboxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 70, 30));

        comboboxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(comboboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 70, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Graficar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 120, 40));

        restablecer.setText("Restablecer");
        restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecerActionPerformed(evt);
            }
        });
        getContentPane().add(restablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 130, 40));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, 130, 40));

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        Grafica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad generada por cada empleado", "Promedio generado en cada mes", "Promedio de ventas anuales", "Cantidad generada en un mes" }));
        Grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficaActionPerformed(evt);
            }
        });
        getContentPane().add(Grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_boleta.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 80, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 300, 40));

        Buscar.setText("Buscar");
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new GUI_Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new GUI_Opciones(rutIngresado).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecerActionPerformed
        DefaultTableModel df = new DefaultTableModel();
        try {
            df = new BDBoleta().cargarBoletas(df);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Tabla.setModel(df);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);
    }//GEN-LAST:event_restablecerActionPerformed

    private void diaAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaAscActionPerformed
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        diaAsc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_Dia(df1, true);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaAscActionPerformed

    private void diaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaDescActionPerformed
        diaAsc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        diaDesc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_Dia(df1, false);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaDescActionPerformed

    private void mesAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesAscActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        mesAsc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_Mes(df1, true);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mesAscActionPerformed

    private void mesDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesDescActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        mesDesc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_Mes(df1, false);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mesDescActionPerformed

    private void anioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioAscActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        anioAsc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_anio(df1, true);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anioAscActionPerformed

    private void anioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioDescActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        canAsc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        canAsc.setEnabled(true);
        canDesc.setEnabled(true);

        anioDesc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_anio(df1, false);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anioDescActionPerformed

    private void canAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canAscActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canDesc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canDesc.setEnabled(true);

        canAsc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_cant(df1, true);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canAscActionPerformed

    private void canDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canDescActionPerformed
        diaAsc.setSelected(false);
        diaDesc.setSelected(false);
        mesAsc.setSelected(false);
        mesDesc.setSelected(false);
        anioAsc.setSelected(false);
        anioDesc.setSelected(false);
        canAsc.setSelected(false);

        diaAsc.setEnabled(true);
        diaDesc.setEnabled(true);
        mesAsc.setEnabled(true);
        mesDesc.setEnabled(true);
        anioAsc.setEnabled(true);
        anioDesc.setEnabled(true);
        canAsc.setEnabled(true);

        canDesc.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        DefaultTableModel df1 = new DefaultTableModel();

        try {
            df1 = new BDBoleta().cargarBoletas_cant(df1, false);
            Tabla.setModel(df1);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canDescActionPerformed

    private void GraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraficaActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        try {
            String selectedItem = (String) Grafica.getSelectedItem();
            if ("Cantidad generada por cada empleado".equals(selectedItem)) {
                new BDBoleta().graficar1();
            } else if ("Promedio generado en cada mes".equals(selectedItem)) {
                String anio = (String) comboboxAnio.getSelectedItem();
                new BDBoleta().graficar2(anio);
            } else if ("Promedio de ventas anuales".equals(selectedItem)) {
                new BDBoleta().graficar3();
            } else if ("Cantidad generada en un mes".equals(selectedItem)) {
                String anio = (String) comboboxAnio.getSelectedItem();
                String mes = (String) comboboxMes.getSelectedItem();
                new BDBoleta().graficar4(anio, mes);
            }

        } catch (SQLException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rut = "";
                try {
                    new GUI_Boleta(rut).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Boleta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> Grafica;
    private javax.swing.JTable Tabla;
    private javax.swing.JRadioButton anioAsc;
    private javax.swing.JRadioButton anioDesc;
    private javax.swing.JRadioButton canAsc;
    private javax.swing.JRadioButton canDesc;
    private javax.swing.JComboBox<String> comboboxAnio;
    private javax.swing.JComboBox<String> comboboxMes;
    private javax.swing.JRadioButton diaAsc;
    private javax.swing.JRadioButton diaDesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelMes;
    private javax.swing.JRadioButton mesAsc;
    private javax.swing.JRadioButton mesDesc;
    private javax.swing.JButton restablecer;
    // End of variables declaration//GEN-END:variables

}
